name: Acessibilidade/projeto/TCC  

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      my-service:
        image: node:16
        ports:
          - 3001:3001
        options: >-
          --health-cmd "curl -f http://localhost:3001/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: |
          npm start &
          sleep 5  # Aguarda 5 segundos para garantir que o servidor inicie
        env:
          NODE_ENV: test

      - name: Wait for server to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3001/; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server to start..."
            sleep 1
          done
          echo "Server did not start in time!"
          exit 1

      - name: Run accessibility tests
        run: npx pa11y http://localhost:3001