name: Acessibilidade CI

on: [push]

jobs:
  test-accessibility:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Instalar dependências
      run: npm install
    - name: Testar acessibilidade
      run: npm run test-a11y