name: Acessibilidade/projeto/TCC

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      my-service:
        image: node:16
        ports:
          - 3001:3001
        options: >-
          --health-cmd "curl -f http://localhost:3001/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Iniciar o servidor
        run: |
          npm start &
          sleep 5  # Aguarda 5 segundos para garantir que o servidor inicie
        env:
          NODE_ENV: test

      - name: Esperar o servidor ficar pronto
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3001/; then
              echo "Servidor está pronto!"
              exit 0
            fi
            echo "Aguardando o servidor iniciar..."
            sleep 1
          done
          echo "O servidor não iniciou a tempo!"
          exit 1

      - name: Executar testes de acessibilidade
        run: npx pa11y http://localhost:3001